# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 14:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0010_auto_20160213_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ord', models.IntegerField(blank=True, default=0)),
                ('name', models.CharField(max_length=80)),
                ('descr', models.CharField(blank=True, max_length=2000, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dati',
                'verbose_name_plural': 'Dati',
            },
        ),
        migrations.CreateModel(
            name='DataContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ord', models.IntegerField(blank=True, default=0)),
                ('name', models.CharField(max_length=80)),
                ('descr', models.CharField(blank=True, max_length=2000, null=True)),
                ('url', models.CharField(max_length=500)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Contenitore dati',
                'verbose_name_plural': 'Contenitori Dati',
            },
        ),
        migrations.CreateModel(
            name='DataTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord', models.IntegerField(blank=True, default=0, null=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataman.Data')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='dataman.Data')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='tasks.Task')),
            ],
            options={
                'ordering': ['task', 'ord'],
                'verbose_name': 'Dipendenza',
                'verbose_name_plural': 'Dipendenze',
            },
        ),
        migrations.AddField(
            model_name='data',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='dataman.DataContainer'),
        ),
        migrations.AddField(
            model_name='data',
            name='content_type',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='data',
            name='dependencies',
            field=models.ManyToManyField(blank=True, null=True, through='dataman.DataTask', to='dataman.Data'),
        ),
    ]
