# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ord', models.IntegerField(blank=True, default=0)),
                ('name', models.CharField(max_length=80)),
                ('descr', models.CharField(blank=True, max_length=2000, null=True)),
                ('max_run', models.IntegerField(blank=True, default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Procedura',
                'verbose_name_plural': 'Procedure',
            },
        ),
    ]
