# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShellTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.Task')),
                ('cmd_line', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name': 'Procedura shell',
                'verbose_name_plural': 'Procedure shell',
            },
            bases=('tasks.task',),
        ),
    ]
