# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrun',
            name='ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
