# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20160115_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedisTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.Task')),
                ('channel', models.CharField(max_length=2000)),
                ('message', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name': 'Procedura Redis',
                'verbose_name_plural': 'Procedure Redis',
            },
            bases=('tasks.task',),
        ),
        migrations.AlterModelOptions(
            name='taskrun',
            options={'ordering': ['task', 'started'], 'verbose_name': 'Esecuzione procedura', 'verbose_name_plural': 'Esecuzioni procedura'},
        ),
        migrations.AlterField(
            model_name='taskrun',
            name='progress',
            field=models.IntegerField(choices=[(-100, 'Fallita'), (-50, 'In ritardo'), (0, 'Creata'), (50, 'Partita'), (100, 'Completa')], default=0),
        ),
        migrations.AlterField(
            model_name='taskrun',
            name='task',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='tasks.Task'),
        ),
    ]
