# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20160210_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='async',
            field=models.BooleanField(default=False, help_text=b'Se selezionato, esegue il task in un processo separato', verbose_name=b'Asincrono'),
        ),
    ]
