# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_async'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.Task')),
                ('channel', models.CharField(max_length=2000)),
                ('message', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'verbose_name': 'Procedura Channel',
                'verbose_name_plural': 'Procedure Channel',
            },
            bases=('tasks.task',),
        ),
        migrations.RemoveField(
            model_name='redistask',
            name='task_ptr',
        ),
        migrations.AlterModelOptions(
            name='shelltask',
            options={'verbose_name': 'Procedura Shell', 'verbose_name_plural': 'Procedure Shell'},
        ),
        migrations.DeleteModel(
            name='RedisTask',
        ),
    ]
